apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "omejdn.fullname" . }}
  labels:
    {{- include "omejdn.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "omejdn.selectorLabels" . | nindent 6 }}
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
      - port: 4567
        protocol: TCP
